CONTRIBUTING.md, README.md
Added a contributing guideline and edited the README to include Tailwind as one of the used technologies
=> Added more documentation

.github/workflows/snyk-security.yml, .github/workflows/sonarcloud.yml
Created sonarcloud.yml in .github/workflows folder to add Sonar Cloud code analysis 
closes #14
=> Added SonarCloud to Github Actions

backend/package-lock.json, backend/package.json
Installed necessary dependencies and configured testing
closes #25
=> set up and configured testing

backend/Documentation.txt, backend/src/config/corsConfig.js, backend/src/config/createTables.js, backend/src/controllers/transactionsController.js, backend/src/controllers/usersController.js, backend/src/middleware/autMiddleware.js, backend/src/routes/transactions.js, backend/src/routes/users.js, backend/src/server.js, backend/src/services/securePassword.js, backend/src/services/transactionService.js, backend/src/services/userService.js
Added the endpoints to allow for setting balance as well as setting goal and getting goal as well 
closes #40
=> Added endpoints for saving goals

frontend/package-lock.json, frontend/package.json
Added axios to the frontend dependencies. This should be used to do HTTP requests to the backend
closes #53
=> Added axios as a dependency

backend/src/config/corsConfig.js, backend/src/controllers/usersController.js, backend/src/services/userService.js, frontend/src/components/CurrentBalance.jsx, frontend/src/pages/Dashboard.jsx
Created a current balance component that takes the data from the backend 
closes #35
=> Added a current balance component

backend/Documentation.txt, frontend/src/utility/transactionFilters.js
Created filters for transactions created the past week, month and day in a utility class. The utility class also contains code to easily make more filters.
closes #61
=> Created transactions filters

frontend/src/components/Transaction.jsx, frontend/src/components/TransactionLog.jsx, frontend/src/pages/Dashboard.jsx, package-lock.json, package.json
Adding transaction log component to the dashboard with reusable transaction sub-component (the red/green text).
resolves #34
=> Adding transaction log component to dashboard

frontend/src/components/AddTransactionButton.jsx, frontend/src/components/DeleteTransactionButton.jsx, frontend/src/pages/Dashboard.jsx, frontend/tailwind.config.js
Adding add/delete transaction buttons to the dashboard, adding tailwind config colours for button hover and click
TODO:
Implement handler functions for both buttons
resolves #36
=> adding add/delete transaction buttons to dashboard

frontend/src/components/TransactionLog.jsx, package-lock.json, package.json
fixing styling issues in transaction log component.
Changes:
- Fixed page number styles not applying
- Fixed page size changing when scrolling through pages
- Added react-icons dependencies 
resolves #82
=> fixing styling issues in transaction log component

frontend/src/components/CurrentBalance.jsx, frontend/src/components/TransactionLog.jsx, frontend/src/context/TransactionContextProvider.jsx, frontend/src/pages/Dashboard.jsx, package-lock.json, package.json
Current balance currency update - adding currency conversion to the balance component.
Changes:
- Refactored TransactionContextProvider to provide balance to all dashboard components (moving balance fetching logic to context provider)
- Adjusted styles of the balance component and adjusted padding around the balance component in the dashboard file
resolves #77
=> Current balance currency update - adding currency conversion to balance component

frontend/src/components/CurrentBalance.jsx, frontend/src/context/TransactionContextProvider.jsx, frontend/src/pages/Dashboard.jsx
renaming variables in CurrentBalance component for codestyle bot.
const [converted, setConvertedAmount] = useState(0); --> const [convertedAmount, setConvertedAmount] = useState(0);
=> Current balance currency update patch - changes made for codestyle bot

frontend/src/components/AddTransactionButton.jsx, frontend/src/components/DeleteTransactionButton.jsx, frontend/src/context/TransactionContextProvider.jsx
Changes:
- Added new requestUiUpdate function to call for a UI update in the transactionContextProvider
- Used new function in delete button
- Fixing components being pushed down when opening mew transaction modal
resolves #100
resolves #102
=> Update transaction log UI when adding/removing transactions

backend/src/controllers/transactionsController.js, backend/src/routes/transactions.js, backend/src/services/transactionService.js
added endpoint for getting all transactions
closes #103
=> added endpoint

backend/src/controllers/transactionsController.js, frontend/src/context/TransactionContextProvider.jsx
Fixed backend server crashing when loggin in.
Issue was that the latest PR was approved but it was never merged for a long time. Between the time of approval and merge, the backend code was changed so when the old PR finally merged its code was no longer compatible with the main repo.
Issue was in transactionsController calling undefined methods and variables.
resolves #116
=> Fix backend crashing when logging in

frontend/src/components/FinancialMetrics.jsx, frontend/src/context/TransactionContextProvider.jsx, frontend/src/pages/Dashboard.jsx
Implemented financial metrics option in dashboard
=> Financial metrics implementation

backend/src/services/userService.js, backend/test/controller/transactionsController.test.js, backend/test/controller/usersController.test.js, backend/test/middleware/authMiddleware.test.js, backend/test/service/securePassword.test.js, backend/test/service/transactionService.test.js, backend/test/service/userService.test.js
Added comments to all the test files.
Achieved 100% branch coverage.
closes #135
=> Test comments

.gitignore, frontend/src/components/DeleteTransactionButton.jsx
Added a disable state to the button while waiting for a response in the handleClick method, plus added a "disabledStyle" to visually indicate that the button is unresponsive
=> Bugfix - Spamming "Delete Transaction" button causes the transaction amount to be removed multiple times

backend/src/services/userService.js, backend/test/service/securePassword.test.js, backend/test/service/transactionService.test.js, backend/test/service/userService.test.js
- add some tests or format code in
- securePassword.test.js
- transactionService.test.js
- userService.test.js
=> refactor/backend testing for services 

frontend/src/components/TransactionForm.jsx
Blocked transaction button from triggering more than once per transaction, and added styles to indicate the buttons are unresponsive. Closes #146
=> Bugfix - Asynchronous errors when adding multiple transactions

backend/src/controllers/transactionsController.js, frontend/src/components/TransactionForm.jsx
=> [Bug] Issue #142: Edge case handling for transaction value of 0

frontend/src/components/LoadingSpinner.jsx, frontend/src/components/transactions/TransactionLog.jsx, frontend/src/context/TransactionContextProvider.jsx
Made the loading spinner appear in initial load, and also centred it's placement.
=> Bugfix/Loading Spinner

frontend/src/components/LoadingSpinner.jsx
Fixed loading spinner placement.
=> bugFix/Loading Spinner Placement

README.md, frontend/src/components/gemini/LuckyAdviser.jsx, frontend/src/components/gemini/ResponseCleaner.jsx
- add instruction on the Gemini API key on the .env section
- how to create Gemini API key
- add Libraries/APIs section
- Recharts
- Gemini API
=> Doc/update README.md

backend/test/controller/luckyAdviserController.test.js, backend/test/service/responseCleaner.test.js
- add tests for backend/src/controllers/luckyAdviserController
- add tests for backend/src/services/responseCleaner.js
=> add tests for gemini api controller and service

frontend/src/components/metrics/BalanceGraph.jsx
=> Feature/Modified graph y-axis to span from 0 to the milestone goal

frontend/src/components/gemini/LuckyAdviser.jsx, frontend/src/components/gemini/LuckyButton.jsx
- match colours of the buttons at the bottom as the buttons in the transaction form
=> consistent submit/cancel btns colours as transactionForm
